{
 "title": "Zookeeper",
 "tags": [ "Kafka Cluster" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Instances Online",
   "type": "graph",
   "description": "Zookeeper",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up{job='zookeeper'}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Packets Received",
   "type": "graph",
   "description": "Packets Received",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_PacketsReceived{job=\"zookeeper\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Packets Sent",
   "type": "graph",
   "description": "Packets Sent",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_PacketsSent{job=\"zookeeper\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "graph",
   "description": "Zookeeper Node Count",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_NodeCount{job=\"zookeeper\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Watch Count",
   "type": "graph",
   "description": "zookeeper watch count",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_WatchCount{job='zookeeper'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Num Alive Connections",
   "type": "graph",
   "description": "zookeeper number alive connections",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_NumAliveConnections{job=\"zookeeper\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "description": "zookeeper outstanding requests",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_OutstandingRequests{job=\"zookeeper\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Min Request Latency",
   "type": "graph",
   "description": "zookeeper min request latency",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_MinRequestLatency{job=\"zookeeper\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "graph",
   "description": "zookeeper average request latency",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_AvgRequestLatency{job=\"zookeeper\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Request Latency",
   "type": "graph",
   "description": "zookeeper max request latency",
   "gridPos": { "h": 6, "w": 8, "x": 24, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_MaxRequestLatency{job=\"zookeeper\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}